<?php

var_dump($tarifas);
?>
<table class="table">
    <tr>
        <th>ID</th>
        <th>Siglas</th>
        <th>Costos Fijos</th>
        <th>Tarifa</th>
    </tr>
    <?php foreach ($tarifas as $tarifa) : ?>
    <tr>
        <td><?= $this->escapeHtml($tarifa->getId()); ?></td>
        <td><?= $this->escapeHtml($tarifa->getAcronym()); ?></td>
        <td><?= $this->escapeHtml($tarifa->getFixedCost()); ?></td>
        <td><?= $this->escapeHtml( json_encode( $tarifa->getSteps() ) ); ?></td>
    </tr>
    <?php endforeach; ?>
</table>