<?php
$title = 'Add new medidor';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
// This provides a default CSS class and placeholder text for the title element:
$numeroServicio = $form->get('numeroServicio');
$numeroServicio->setAttribute('class', 'form-control');
$numeroServicio->setAttribute('placeholder', 'Numero de Servicio');

// This provides a default CSS class and placeholder text for the artist element:
$titular = $form->get('titular');
$titular->setAttribute('class', 'form-control');
$titular->setAttribute('placeholder', 'Titular');

// This provides a default CSS class and placeholder text for the artist element:
$tarifa = $form->get('tarifa');
$tarifa->setAttribute('class', 'form-control');
$tarifa->setAttribute('placeholder', 'Tarifa');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('medidor', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>
<div class="form-group">
    <?= $this->formLabel($numeroServicio) ?>
    <?= $this->formElement($numeroServicio) ?>
    <?= $this->formElementErrors()->render($numeroServicio, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($titular) ?>
    <?= $this->formElement($titular) ?>
    <?= $this->formElementErrors()->render($titular, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($tarifa) ?>
    <?= $this->formElement($tarifa) ?>
    <?= $this->formElementErrors()->render($tarifa, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();